richPurba | 2020-04-25 12:13:20 UTC | #1

Hi There

Not sure what has happened with  `dfx start`, i received the following error: 

`
 $dfx start
⠁ Starting up the client...
thread 'main' panicked at 'Couldn't start executable: Sys(ENOENT)', src/libcore/result.rs:1165:5
⠈ Replica exited with exit code: 101
An error occured:
AgentError(
    TimeoutWaitingForResponse,`

I tried to uninstall and reinstall (version 0.5.5) but the problem still persists. Upon checking, it seems this is in the rust compiler, but i have no access to the source code thus no clue what is going on. 
When using `dfx -v start` there is no verbosity of outputs produced (exactly the same as above). 
I understand that this is still in alpha version, but any clear explanation is most welcomed!

Best,

-------------------------

Ori | 2020-04-25 15:32:04 UTC | #2

If this isn’t a new project, try dfx start --clean, though this might not be a checkpoint issue. 

For more error details you could try running with the RUST_BACKTRACE environment variable set to 1 or full, eg:

`env RUST_BACKTRACE=full dfx start`

-------------------------

richPurba | 2020-04-25 19:45:10 UTC | #3

Hi Ori

Thanks for the stack trace option. I actually check for both old projects and also created a new one with `dfx new` but the same result when i `dfx start` (tho `build` works just fine).

With the `--clean`, no real result. 
i just created a new project with `dfx new test` and it's the same response. But when i use the `env RUST_...etc` the followings appear (don't know if there is any clue to this):

`env RUST_BACKTRACE=full dfx start
 Starting up the client...
thread 'main' panicked at 'Couldn't start executable: Sys(ENOENT)', src/libcore/result.rs:1165:5
stack backtrace:
   0:        0x106e396c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h355adbfea9b69e81
   1:        0x106e573e1 - core::fmt::write::h0a6fa03a6719e234
   2:        0x106e37a09 - std::io::Write::write_fmt::h4ee006266df2263e
   3:        0x106e3cc34 - std::panicking::default_hook::{{closure}}::ha12dae99d957e66b
   4:        0x106e3c962 - std::panicking::default_hook::h44527206a56250c5
   5:        0x106e3d2bb - std::panicking::rust_panic_with_hook::hbd167ed9e2c235b1
   6:        0x106e3ce19 - std::panicking::continue_panic_fmt::h75e9347d75167545
   7:        0x106e3cd19 - rust_begin_unwind
   8:        0x106e56efc - core::panicking::panic_fmt::h001cf11361048a09
   9:        0x106e5b509 - core::result::unwrap_failed::h5fc509d43c77f16c
  10:        0x106e24dbd - packager::main::hefb81253650f4d0d
  11:        0x106e26626 - std::rt::lang_start::{{closure}}::h503c755c140699db
  12:        0x106e3ccf8 - std::panicking::try::do_call::hfb024a99db52bb27
  13:        0x106e43aef - __rust_maybe_catch_panic
  14:        0x106e4265b - std::rt::lang_start_internal::h6e149180bd1da82a
⠉ Replica exited with exit code: 101
An error occured:
AgentError(
    TimeoutWaitingForResponse,
)`

-------------------------

chenyan | 2020-04-25 21:08:40 UTC | #4

Can you try `rm -rf $TMPDIR/ic-*`

-------------------------

matthewhammer | 2020-05-04 23:43:03 UTC | #5

FWIW, this now helps me overcome the same issue (`dfx start` not succeeding, and timing out)

-------------------------

