lastmjs | 2021-11-24 02:18:24 UTC | #1

I am using dfx v0.8.4. I am trying to do a cross-canister call to the management canister like I've done before:

```rust
let call_result: Result<(Vec<u8>,), _> = ic_cdk::api::call::call(
    ic_cdk::export::Principal::management_canister(),
    // ic_cdk::export::Principal::from_text("aaaaa-aa").unwrap(),
    "raw_rand",
    ()
).await;
```

Each way of calling the management canister above (one is commented out) results in the following error:

```bash
[Canister rrkah-fqaaa-aaaaa-aaaaq-cai] Panicked at 'called `Result::unwrap()` on an `Err` value: (DestinationInvalid, "Canister o5alr-fkgwv-ukoa3-em3wh-7cj4t-ngizi-krl3c-v44po-ar5jg-a5agw-pqe not found")', canisters/call/src/lib.rs:125:44
```

-------------------------

ielashi | 2021-11-24 05:54:04 UTC | #2

Are you trying to do this within a query call? Cross-canister queries are not yet supported, and so the method must be an update call for it to work.

-------------------------

