Zane | 2023-04-03 07:02:32 UTC | #1

When deploying a project on dfx 0.13.1 I get this error everytime I start the replica without the 
--clean argument.
>Failed to get wallet canister caller for identity 'default' on network 'local'

When the replica starts I also get this warning, not sure if it could be related:

>Using the default definition for the 'local' shared network because /home/user/.config/dfx/networks.json does not exist.

-------------------------

Severin | 2023-04-03 11:26:22 UTC | #2

Hmm, this sounds weird. Maybe the wallets don't get updated properly? Can you inspect this file a bit closer at different stages in the process? And say what kind of system you're on (Linux, Macos)?
```
$HOME/.local/share/dfx/network/local/wallets.json (Linux)
$HOME/Library/Application Support/org.dfinity.dfx/network/local.json (Macos)
```

Also, can you please confirm the minimal steps required to reproduce the problem are as follows:
1. `dfx start --clean`
2. `dfx deploy`
3. `dfx stop`
4. `dfx start`
5. `dfx deploy` <- fails with the above error

-------------------------

Zane | 2023-04-03 18:06:21 UTC | #3

I'm on Linux, this is what's inside wallet.json:

>  "identities": {
    "default": {
      "local": "rwlgt-iiaaa-aaaaa-aaaaa-cai"
    }

When I start with --clean it gets deleted and when doing dfx start it gets recreated with the same value.

[quote="Severin, post:2, topic:19245"]
Also, can you please confirm the minimal steps required to reproduce the problem are as follows:
[/quote]

Yes that is correct

-------------------------

Severin | 2023-04-04 10:18:26 UTC | #4

Perfect, thanks. I'll note it in our bug reports (note to self: [ticket](https://dfinity.atlassian.net/browse/SDK-1070)), but I can't make any promises - this looks like a bug that is very hard to reproduce.

-------------------------

