hecateq | 2023-10-24 22:13:05 UTC | #1

Hi guys, Iâ€˜m having this error:

  The Replica returned an error: code 5, message: "Canister <CanisterID> trapped explicitly: assertion failed at heca.mo:218.3-218.32"

Here are the lines 217-220 in heca.mo:

public shared(msg) func setFrontendCanister(canisterID : Text) : async {
    assert(msg.caller == _minter, "Only the minter can call this function.");
    _frontendCanister := canisterID;
};

How can I fix this error?

-------------------------

infu | 2023-10-24 22:33:02 UTC | #2

Doesn't look like a bug. It's working as intended. 
You need to see what sets _minter and set it to your principal before calling this function

-------------------------

